[build]
builder = "nixpacks"
providers = ["node"]
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
